name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_email:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check PR Author's Email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          par=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/than57/repo/pulls/${PR_NUMBER}/commits"| jq -r '.[-1].commit.author.email')

          if [[ $par == *"@mobven.com"* ]]; then
             echo "PR author's email match '@mobven.com'. Accept the PR..."
             curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"Email address has been verified.\"}" "https://api.github.com/repos/than57/repo/issues/${PR_NUMBER}/comments"
          else
            echo "PR author's email does not match 'tolgahanakcaa@gmail.com'. Rejecting the PR..."
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"Sorry, pull requests from users with non-matching email are not accepted.\"}" "https://api.github.com/repos/mobven/devops-kit/issues/${PR_NUMBER}/comments"
            curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d "{\"state\": \"closed\"}" "https://api.github.com/repos/mobven/devops-kit/pulls/${PR_NUMBER}"
          fi
