name: Jit.io Scan
on:
  push:
    branches:
      - test
      - master
jobs:
  jit-io-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jitsecurity-controls/jit-github-action@v1.1.0
        with:
          token: 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
    if: github.event.pull_request.draft == false
